# Generated by Django 4.2.3 on 2023-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_managers_alter_account_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='site',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
