# Generated by Django 4.2.3 on 2023-07-22 15:56

import app.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('whatsapp_number', models.CharField(max_length=32)),
                ('device_uuid', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ManyToManyField(related_name='visitors', to='app.account')),
            ],
            managers=[
                ('objects', app.managers.VisitorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=64)),
                ('device', models.CharField(max_length=64)),
                ('page_name', models.CharField(max_length=128)),
                ('page_url', models.URLField(max_length=2000)),
                ('button_clicked', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=64)),
                ('time_stayed', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='app.account')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='app.visitor')),
            ],
        ),
    ]
