# Generated by Django 4.2.3 on 2023-07-22 21:36

import app.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_visitor_analytics'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analytics',
            managers=[
                ('objects', app.managers.AnalyticsManager()),
            ],
        ),
        migrations.AlterField(
            model_name='analytics',
            name='browser',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='button_clicked',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='device',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='page_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='page_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='time_stayed',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
