# Generated by Django 4.1 on 2023-08-24 19:41

import app.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_watiattribute_managers_watitemplate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='watitemplate',
            managers=[
                ('objects', app.managers.WatiTemplateManager()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSegmentationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('segmentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.segmentation')),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.visitor')),
            ],
        ),
    ]
