# Generated by Django 4.2.3 on 2023-07-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_analytics_managers_alter_analytics_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='time_stayed',
        ),
    ]
