# Generated by Django 4.2.3 on 2023-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_analytics_time_stayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='time_stayed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
