# Generated by Django 4.1 on 2023-08-22 06:59

import app.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_watiattribute'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='watiattribute',
            managers=[
                ('objects', app.managers.WatiAttributeManager()),
            ],
        ),
        migrations.CreateModel(
            name='WatiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wati_template', to='app.account')),
            ],
        ),
    ]
