# Generated by Django 4.1 on 2023-08-23 22:11

import app.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_watiattribute_managers_watitemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.account')),
            ],
            managers=[
                ('objects', app.managers.CampaignManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Starting message'), (1, 'On message delivered'), (2, 'ON message read'), (3, 'On message replied')], default=0)),
                ('schedule', models.IntegerField(default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.campaign')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='app.message')),
            ],
        ),
        migrations.AlterModelManagers(
            name='watitemplate',
            managers=[
                ('objects', app.managers.WatiTemplateManager()),
            ],
        ),
        migrations.CreateModel(
            name='WatiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wati_message_id', models.CharField(default=None, max_length=128, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wati_messages', to='app.message')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wati_messages', to='app.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.watitemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.message'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.segmentation'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('parent', 'action')},
        ),
    ]
