# Generated by Django 4.1 on 2023-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_campaign_message_alter_message_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
